#!/bin/bash
test -z "$1" && exit 1
Color='\033[0;33m'
test1=$(curl --connect-timeout 5 --max-time 5 --retry 5 --retry-delay 0 --retry-max-time 10 -ks "https://cotacao.b3.com.br/mds/api/v1/InstrumentQuotation/$1" -H "Accept: application/json" | jq)
test2=$(echo "$test1" | jq '.Trad[0].scty.SctyQtn.prcFlcn')
test3=$(echo "$test1" | jq '.Trad[0].scty.SctyQtn.curPrc')
printf "\n"
printf ${Color} 
printf $1
printf ": "
echo $test2 | tr -d '\n'
printf "%%"
printf "     "
printf "R$ "
echo $test3 | tr -d '\n'
printf "\n"
printf "\n"